src/Entity/Articles.php
<?php

namespace App\Entity;

use App\Repository\ArticlesRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticlesRepository::class)]
class Articles
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $Excerpt = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getExcerpt(): ?string
    {
        return $this->Excerpt;
    }

    public function setExcerpt(string $Excerpt): self
    {
        $this->Excerpt = $Excerpt;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }
}

src/Controller/ArticlesController.php
<?php

namespace App\Controller;

use App\Repository\ArticlesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ArticlesController extends AbstractController
{
    public function __construct(ArticlesRepository $repo)
    {
        $this->repo = $repo;
    }

    #[Route('/article', name: 'app_articles')]
    public function index(): Response
    {
        $articles = $this->repo->findAll();
        return $this->render('articles/index.html.twig', [
            'articles' => $articles,
        ]);
    }

    #[Route('/articles/{id}', name: 'articles.show', methods: ['GET'])]
    public function show($id, ArticlesRepository $ARRepo): Response
    {
        $articles = $this->repo->find($id);

        return $this->render('articles/show.html.twig', ['article' => $articles]);
    }
}

templates/articles/index.html.twig
{% extends 'layout/default.html.twig' %}

{% block header %}
  <header class="masthead text-center text-white">
    <div class="masthead-content">
      <div class="container px-5">
        <h1 class="masthead-heading mb-0">
          Liste des articles
        </h1>
      </div>
    </div>
  </header>
{% endblock %}

{% block content %}
  {% for articles in articles %}
    <div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
          <!-- Post preview -->
          <div class="post-preview">
            <a href="articles/{{ articles.id }}">
              <hr />
              <h1 class="post-title">
                {{ articles.title }}
              </h1>
              <p>
                {{ articles.description }}
              </p>
              <h3 class="post-subtitle">
                {{ articles.excerpt }}
              </h3>
            </a>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
{% endblock %}

templates/articles/show.html.twig
{% extends 'layout/default.html.twig' %}

{% block header %}

  <header class="masthead text-center text-white">
    <div class="masthead-content">
      <div class="container px-5">
        <h1 class="masthead-heading mb-0">
     Afficher un article
        </h1>
      </div>
    </div>
  </header>

{% endblock %}

{% block content %}
  <div class="container px-5">
    <div class="row gx-5 align-items-center">
      <div class="col-lg-6 order-lg-2">
        <h1 class="post-title"> {{ article.title }} </h1>
       </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <p>
            {{ article.excerpt }}
          </p>          
        </div>
      </div>
    </div>
  </div>
{% endblock %}